package model;

import jakarta.persistence.*;

import java.time.LocalTime;

//TODO  autogenerated getters and setters, review PKS, Recursive table

//need bit to days converter


@Entity (name = "TIMESLOTS")
@Table(uniqueConstraints={
        @UniqueConstraint(columnNames = {"startTime", "endTime","daysofWeek"})})
public class TimeSlot {
    enum daysofWeek{
        Monday(32) , Tuesday(16), Wednesday(8), Thursday(4), Friday(2), Saturday(1), Sunday(64);

        public int bitFlag;

        daysofWeek(int bitFlag) {
            this.bitFlag = bitFlag;
        }

        public int getBitFlag() {
            return bitFlag;
        }
    }

    //pk
    @Id
    @Column(name = "timeslot_id")
    @GeneratedValue (strategy = GenerationType.IDENTITY)
    private int timeSlotId;

    //class attributes
    @Column(nullable = false)
    private byte daysOfWeek;

    @Column(nullable = false)
    private LocalTime startTime;

    @Column(nullable = false)
    private LocalTime endTime;

    public TimeSlot(){

    }

    public TimeSlot(byte daysOfWeek, LocalTime startTime, LocalTime endTime) {
        this.daysOfWeek = daysOfWeek;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public int getTimeSlotId() {
        return timeSlotId;
    }

    public void setDaysOfWeek(byte daysOfWeek) {
        this.daysOfWeek = daysOfWeek;
    }

    public LocalTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    public LocalTime getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }
}
